import { Button } from "@/components/ui/button";
import { Camera, FileText, MessageCircle, Shield, Zap } from "lucide-react";
import Link from "next/link";

export default function ProductPage() {
    return (
        <div className="flex flex-col min-h-screen">
            {/* Product Hero */}
            <section className="py-20 bg-background">
                <div className="container mx-auto px-4 text-center">
                    <h1 className="text-4xl md:text-5xl font-bold mb-6 bg-clip-text text-transparent bg-gradient-to-r from-cyan-400 to-blue-500">
                        Sniff by Hatch
                    </h1>
                    <p className="text-xl text-muted-foreground max-w-2xl mx-auto mb-10">
                        The intelligent health assistant for your pet. Early detection, instant analysis, and professional guidance in one app.
                    </p>
                    <div className="relative w-full max-w-4xl mx-auto aspect-video rounded-2xl overflow-hidden border border-white/10 shadow-2xl bg-zinc-900 flex items-center justify-center group">
                        <div className="absolute inset-0 bg-gradient-to-t from-black/80 to-transparent z-10"></div>
                        <div className="z-20 text-center p-8">
                            <span className="text-white/50 text-lg group-hover:text-white/80 transition-colors">App Interface Demo Preview</span>
                        </div>
                        {/* Placeholder for App Screenshot */}
                        <div className="absolute inset-0 bg-[url('https://images.unsplash.com/photo-1551730459-92db2a308d6b?q=80&w=2574&auto=format&fit=crop')] bg-cover bg-center opacity-40"></div>
                    </div>
                </div>
            </section>

            {/* How it Works */}
            <section className="py-20 bg-secondary/20">
                <div className="container mx-auto px-4">
                    <h2 className="text-3xl font-bold text-center mb-16">How It Works</h2>
                    <div className="grid grid-cols-1 md:grid-cols-3 gap-8">
                        <div className="flex flex-col items-center text-center">
                            <div className="h-16 w-16 rounded-full bg-cyan-500/20 flex items-center justify-center mb-6 text-cyan-400">
                                <Camera className="h-8 w-8" />
                            </div>
                            <h3 className="text-xl font-bold mb-3">1. Snap a Photo</h3>
                            <p className="text-muted-foreground">
                                Take a clear picture of your pet's skin, teeth, or area of concern. Our vision model identifies visual symptoms instantly.
                            </p>
                        </div>
                        <div className="flex flex-col items-center text-center">
                            <div className="h-16 w-16 rounded-full bg-purple-500/20 flex items-center justify-center mb-6 text-purple-400">
                                <MessageCircle className="h-8 w-8" />
                            </div>
                            <h3 className="text-xl font-bold mb-3">2. Chat with AI</h3>
                            <p className="text-muted-foreground">
                                Answer a few context-aware questions generated by our LLM to provide a complete health history.
                            </p>
                        </div>
                        <div className="flex flex-col items-center text-center">
                            <div className="h-16 w-16 rounded-full bg-emerald-500/20 flex items-center justify-center mb-6 text-emerald-400">
                                <FileText className="h-8 w-8" />
                            </div>
                            <h3 className="text-xl font-bold mb-3">3. Get Report</h3>
                            <p className="text-muted-foreground">
                                Receive a comprehensive health analysis report with care recommendations and vet referral if needed.
                            </p>
                        </div>
                    </div>
                </div>
            </section>

            {/* Detailed Features */}
            <section className="py-20">
                <div className="container mx-auto px-4">
                    <div className="grid grid-cols-1 md:grid-cols-2 gap-16 items-center mb-20">
                        <div>
                            <h3 className="text-2xl font-bold mb-4 flex items-center">
                                <Zap className="h-6 w-6 text-yellow-400 mr-2" />
                                Advanced Image Analysis
                            </h3>
                            <p className="text-muted-foreground mb-6">
                                Our proprietary vision models are trained on thousands of veterinary dermatology and dental images. They can detect:
                            </p>
                            <ul className="space-y-2 text-muted-foreground">
                                <li className="flex items-center"><span className="h-1.5 w-1.5 rounded-full bg-cyan-400 mr-2"></span>Skin rashes and infections</li>
                                <li className="flex items-center"><span className="h-1.5 w-1.5 rounded-full bg-cyan-400 mr-2"></span>Dental grade and tartar buildup</li>
                                <li className="flex items-center"><span className="h-1.5 w-1.5 rounded-full bg-cyan-400 mr-2"></span>Wound severity and healing progress</li>
                                <li className="flex items-center"><span className="h-1.5 w-1.5 rounded-full bg-cyan-400 mr-2"></span>Ocular discharge and redness</li>
                            </ul>
                        </div>
                        <div className="h-[300px] rounded-2xl bg-gradient-to-br from-cyan-900/20 to-blue-900/20 border border-white/10 flex items-center justify-center">
                            <span className="text-muted-foreground/50">Image Analysis Visualization</span>
                        </div>
                    </div>

                    <div className="grid grid-cols-1 md:grid-cols-2 gap-16 items-center">
                        <div className="order-2 md:order-1 h-[300px] rounded-2xl bg-gradient-to-br from-emerald-900/20 to-teal-900/20 border border-white/10 flex items-center justify-center">
                            <span className="text-muted-foreground/50">Vet Dashboard Visualization</span>
                        </div>
                        <div className="order-1 md:order-2">
                            <h3 className="text-2xl font-bold mb-4 flex items-center">
                                <Shield className="h-6 w-6 text-emerald-400 mr-2" />
                                Vet-in-the-Loop
                            </h3>
                            <p className="text-muted-foreground mb-6">
                                We don't guess. When the AI detects high-risk signals, the case is flagged for review by our partner veterinarians.
                            </p>
                            <p className="text-muted-foreground">
                                You get the speed of AI with the safety net of human expertise. Reports include specific actionable advice: "Monitor at home", "Schedule non-urgent visit", or "Visit ER immediately".
                            </p>
                        </div>
                    </div>
                </div>
            </section>

            {/* CTA */}
            <section className="py-20 border-t border-white/5 bg-secondary/10 text-center">
                <div className="container mx-auto px-4">
                    <h2 className="text-3xl font-bold mb-6">Experience the Future of Pet Care</h2>
                    <Link href="/pricing">
                        <Button size="lg" variant="premium">
                            Check Your Pet's Health
                        </Button>
                    </Link>
                </div>
            </section>
        </div>
    );
}
